name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: freckle/stack-cache-action@v2
      - id: stack
        uses: freckle/stack-action@v5
      - uses: freckle/weeder-action@v3
        with:
          ghc-version: ${{ steps.stack.outputs.compiler-version }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: haskell/actions/hlint-setup@v2
      - uses: haskell/actions/hlint-run@v2
        with:
          fail-on: warning
